// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCWeAoekHBvyPgMg2JqScoJ7SUtwKmW5pQ',
    appId: '1:672271550387:web:8efab75756c94a226d2dc6',
    messagingSenderId: '672271550387',
    projectId: 'turf-buddies',
    authDomain: 'turf-buddies.firebaseapp.com',
    storageBucket: 'turf-buddies.appspot.com',
    measurementId: 'G-CPRTK0ESVL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCv9o_K7mbPmu4k45Uft-JDzzt7Y8FwIOE',
    appId: '1:672271550387:android:3575eaffe414400a6d2dc6',
    messagingSenderId: '672271550387',
    projectId: 'turf-buddies',
    storageBucket: 'turf-buddies.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCt8Ug_dixZeyP1EF7WPW3_8aXKHzMZwTY',
    appId: '1:672271550387:ios:a49a249fce7a4d526d2dc6',
    messagingSenderId: '672271550387',
    projectId: 'turf-buddies',
    storageBucket: 'turf-buddies.appspot.com',
    androidClientId: '672271550387-7obeifj0ir2gjprsbbrnned3t1p37kna.apps.googleusercontent.com',
    iosClientId: '672271550387-m665pjni9cf3ldbroj7e7dmdnnm1rgm7.apps.googleusercontent.com',
    iosBundleId: 'com.example.tbWeb',
  );
}
